### ISSUE TITLE
No response messages in chat

### ISSUE THREAD

**Issue by blue-pinapple** [amsam0/voicechat-discord#70]
**Describe the bug**

**To Reproduce**
1. type `/dvc group list` or any other command
2. See no reply

**Expected behavior**
I expect that there is meant to be some kind of response when I run a command. When I run it in the console I get
```logs
25.09 05:47:55 [Server] INFO There are currently no groups.
```

**Logs**
```
[05:51:18] [Server thread/INFO]: Blue7657 issued server command: /dvc reloadconfig
[05:51:19] [voicechat-discord: Reload Config/INFO]: [voicechat-discord] Using 8 bots
[05:51:19] [voicechat-discord: Reload Config/INFO]: [voicechat-discord] Debug level has been set to 3
[05:51:37] [Server thread/INFO]: Blue7657 issued server command: /dvc group list
[05:51:55] [Server thread/INFO]: Blue7657 issued server command: /dvc checkforupdate
[05:51:55] [voicechat-discord: Check for Update/INFO]: [voicechat-discord] [DEBUG 2] Found tag: 3.0.5
[05:51:55] [voicechat-discord: Check for Update/INFO]: [voicechat-discord] [DEBUG 2] Found tag: 3.0.4
[05:51:55] [voicechat-discord: Check for Update/INFO]: [voicechat-discord] [DEBUG 2] Found tag: 3.0.3
[05:51:55] [voicechat-discord: Check for Update/INFO]: [voicechat-discord] [DEBUG 2] Found tag: 3.0.2
[05:51:55] [voicechat-discord: Check for Update/INFO]: [voicechat-discord] [DEBUG 2] Found tag: 3.0.1
[05:51:55] [voicechat-discord: Check for Update/INFO]: [voicechat-discord] [DEBUG 2] Found tag: 3.0.0
[05:51:55] [voicechat-discord: Check for Update/INFO]: [voicechat-discord] [DEBUG 2] Found tag: 2.1.1
[05:51:55] [voicechat-discord: Check for Update/INFO]: [voicechat-discord] [DEBUG 2] Found tag: 2.1.0
[05:51:55] [voicechat-discord: Check for Update/INFO]: [voicechat-discord] [DEBUG 2] Found tag: 2.0.1
[05:51:55] [voicechat-discord: Check for Update/INFO]: [voicechat-discord] [DEBUG 2] Found tag: 2.0.0
[05:51:55] [voicechat-discord: Check for Update/INFO]: [voicechat-discord] [DEBUG 2] Found tag: 1.4.0
[05:51:55] [voicechat-discord: Check for Update/INFO]: [voicechat-discord] [DEBUG 2] Found tag: 1.3.0
[05:51:55] [voicechat-discord: Check for Update/INFO]: [voicechat-discord] [DEBUG 2] Found tag: 1.2.0
[05:51:55] [voicechat-discord: Check for Update/INFO]: [voicechat-discord] [DEBUG 2] Found tag: 1.1.0
[05:51:55] [voicechat-discord: Check for Update/INFO]: [voicechat-discord] [DEBUG 2] Found tag: 1.0.0
[05:51:55] [voicechat-discord: Check for Update/INFO]: [voicechat-discord] [DEBUG 2] Found tag: 1.0.0-build4
[05:51:55] [voicechat-discord: Check for Update/INFO]: [voicechat-discord] [DEBUG 2] Found tag: 1.0.0-build3
[05:51:55] [voicechat-discord: Check for Update/INFO]: [voicechat-discord] [DEBUG 2] Found tag: 1.0.0-build2
[05:51:55] [voicechat-discord: Check for Update/INFO]: [voicechat-discord] [DEBUG 1] Current version is 3.0.5, latest version is 3.0.5
```
Other key parts of log
```
[05:07:17] [Server thread/INFO]: [voicechat-discord] Successfully initialized Simple Voice Chat plugin
[05:07:17] [Server thread/INFO]: [voicechat] Initialized 1 plugin(s)
[05:07:17] [Server thread/INFO]: [voicechat] Registering events for 'voicechat-discord'
[VoiceChatServerThread/ERROR]: [voicechat] Failed to parse bind IP address '<IP> '
java.net.UnknownHostException: <IP> : Name or service not known
	at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[?:?]
	at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:52) ~[?:?]
	at java.base/java.net.InetAddress$PlatformResolver.lookupByName(InetAddress.java:1211) ~[?:?]
	at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1828) ~[?:?]
	at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:1139) ~[?:?]
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1818) ~[?:?]
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1688) ~[?:?]
	at java.base/java.net.InetAddress.getByName(InetAddress.java:1568) ~[?:?]
	at voicechat-bukkit-2.5.20.jar/de.maxhenkel.voicechat.plugins.impl.VoicechatSocketImpl.open(VoicechatSocketImpl.java:23) ~[voicechat-bukkit-2.5.20.jar:?]
	at voicechat-bukkit-2.5.20.jar/de.maxhenkel.voicechat.voice.server.Server.run(Server.java:78) ~[voicechat-bukkit-2.5.20.jar:?]
[05:07:17] [VoiceChatServerThread/INFO]: [voicechat] Binding to wildcard IP address
```
**Versions (please complete the following information):**
- Minecraft: 1.21.1
- Loader: paper
- Simple Voice Chat: 2.5.20
- Simple Voice Chat Discord Bridge: 3.0.5

**Context**
The bots do turn on and connect to the call (unable to test if it sends audio)
Some plugins that could affect this is:
PerWordPlugins (set to ignore dvc)
EssentialsX
ViaVersion
A few different building plugins
Voicechat-interactive
Geyser

**Comment by amsam0** [comment]
Please disable all plugins. I think you have a plugin that is interfering with the players receiving messages this addon sends.

**Comment by blue-pinapple** [comment]
I will have to create a test server and get back to you as soon as possible

**Comment by blue-pinapple** [comment]
After a server restart and only one change that I know of it seems to be working
the bind address on simple VC was wrong and fixing it seemed to allow response messages to send
Thanks for helping anyway
