### ISSUE TITLE
Well, I can't create the folder and this error always appears. I've tried other versions of the plugin but it didn't work.

### ISSUE THREAD

**Issue by Krius-krow** [amsam0/voicechat-discord#72]
[13:10:14 ERROR]: [voicechat] Failed to initialize plugin 'voicechat-discord'
java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(ZipFile.java:840) ~[?:?]
        at java.util.zip.ZipFile.getEntry(ZipFile.java:339) ~[?:?]
        at java.util.jar.JarFile.getEntry(JarFile.java:517) ~[?:?]
        at java.util.jar.JarFile.getJarEntry(JarFile.java:472) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:195) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:592) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:155) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at dev.naturecodevoid.voicechatdiscord.Plugin.initialize(Plugin.java:20) ~[voicechat-discord-bukkit-1.2.0.jar:?]
        at de.maxhenkel.voicechat.plugins.PluginManager.init(PluginManager.java:40) ~[voicechat-bukkit-2.5.24.jar:?]
        at de.maxhenkel.voicechat.Voicechat.lambda$onEnable$0(Voicechat.java:128) ~[voicechat-bukkit-2.5.24.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-550]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1115) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-550]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

**Comment by amsam0** [comment]
That is not the whole error. Please send complete logs. I also need to know server type, server version, and addon version.

**Comment by amsam0** [comment]
@Krius-krow Please see the above message or I will close this issue as invalid

**Comment by Krius-krow** [comment]
eu consegui resolver, baixando uma versão antiga do addon, as novas continuaram dando erro, a versão spigot e bukkit deram mais erro que o normal

**Comment by amsam0** [comment]
@Krius-krow PaperMC is required for current versions.
