### ISSUE TITLE
mohistmc 1.20.1 - Java 21

### ISSUE THREAD

**Issue by ramharan** [amsam0/voicechat-discord#73]
[21:16:37 ERROR]: Error occurred while enabling voicechat-discord v3.0.5 (Is it up to date?)
java.lang.NoSuchMethodError: 'java.lang.String org.bukkit.Server.getMinecraftVersion()'
        at dev.amsam0.voicechatdiscord.PaperPlugin.onEnable(PaperPlugin.java:40) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:347) ~[forge-1.20.1-47.2.23-universal.jar%23337!/:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336) ~[forge-1.20.1-47.2.23-universal.jar%23337!/:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:482) ~[forge-1.20.1-47.2.23-universal.jar%23337!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:549) ~[forge-1.20.1-47.2.23-universal.jar%23337!/:997de31d-ddc9a2dad-d2eba2c8-47.1.79]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:462) ~[forge-1.20.1-47.2.23-universal.jar%23337!/:997de31d-ddc9a2dad-d2eba2c8-47.1.79]
        at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:441) ~[server-1.20.1-20230612.114412-srg.jar%23332!/:?]
        at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:341) ~[server-1.20.1-20230612.114412-srg.jar%23332!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:224) ~[server-1.20.1-20230612.114412-srg.jar%23332!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:848) ~[server-1.20.1-20230612.114412-srg.jar%23332!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281) ~[server-1.20.1-20230612.114412-srg.jar%23332!/:?]
        at java.lang.Thread.run(Thread.java:1583) [?:?]
[21:16:37 INFO]: [voicechat-discord] Disabling voicechat-discord v3.0.5
[21:16:38 INFO]: Shutting down 0 bots
[21:16:38 INFO]: Successfully shutdown 0 bots
[21:16:38 ERROR]: Error occurred while disabling voicechat-discord v3.0.5 (Is it up to date?)
java.lang.UnsatisfiedLinkError: 'void dev.amsam0.voicechatdiscord.Core.shutdownNatives()'
        at dev.amsam0.voicechatdiscord.Core.shutdownNatives(Native Method) ~[?:?]
        at dev.amsam0.voicechatdiscord.Core.disable(Core.java:60) ~[?:?]
        at dev.amsam0.voicechatdiscord.PaperPlugin.onDisable(PaperPlugin.java:91) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:349) ~[forge-1.20.1-47.2.23-universal.jar%23337!/:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:365) ~[forge-1.20.1-47.2.23-universal.jar%23337!/:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:507) ~[forge-1.20.1-47.2.23-universal.jar%23337!/:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) ~[forge-1.20.1-47.2.23-universal.jar%23337!/:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:482) ~[forge-1.20.1-47.2.23-universal.jar%23337!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:549) ~[forge-1.20.1-47.2.23-universal.jar%23337!/:997de31d-ddc9a2dad-d2eba2c8-47.1.79]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:462) ~[forge-1.20.1-47.2.23-universal.jar%23337!/:997de31d-ddc9a2dad-d2eba2c8-47.1.79]
        at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:441) ~[server-1.20.1-20230612.114412-srg.jar%23332!/:?]
        at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:341) ~[server-1.20.1-20230612.114412-srg.jar%23332!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:224) ~[server-1.20.1-20230612.114412-srg.jar%23332!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:848) ~[server-1.20.1-20230612.114412-srg.jar%23332!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281) ~[server-1.20.1-20230612.114412-srg.jar%23332!/:?]
        at java.lang.Thread.run(Thread.java:1583) [?:?]

**Comment by amsam0** [comment]
Just like Simple Voice Chat, we do not provide support for hybrid server software. Please make a bug report on your hybrid server software's GitHub
