### ISSUE TITLE
Crash when /dvc start

### ISSUE THREAD

**Issue by laroweb** [amsam0/voicechat-discord#76]
**Describe the bug**
When someone do /dvc start, the server crash

.BIGYan008 issued server command: /dvc start
[02:01:26 INFO]: [voicechat-discord] Started voice chat for .BIGYan008 in channel Vocal proximité 1 with bot with vc_id 1277425357917655050
[02:01:53 ERROR]: [voicechat] Uncaught exception in thread VoiceChatPacketProcessingThread
java.lang.NoSuchMethodError: 'org.bukkit.command.CommandSender net.minecraft.world.entity.Entity.getBukkitSender(net.minecraft.commands.CommandSourceStack)'
        at voicechat-discord-paper-3.0.5.jar/dev.amsam0.voicechatdiscord.PaperPlatform.getEntityPosition(PaperPlatform.java:59) ~[voicechat-discord-paper-3.0.5.jar:?]
        at voicechat-discord-paper-3.0.5.jar/dev.amsam0.voicechatdiscord.PaperPlatform.getEntityPosition(PaperPlatform.java:84) ~[voicechat-discord-paper-3.0.5.jar:?]
        at voicechat-discord-paper-3.0.5.jar/dev.amsam0.voicechatdiscord.DiscordBot.handlePacket(DiscordBot.java:285) ~[voicechat-discord-paper-3.0.5.jar:?]
        at voicechat-bukkit-2.5.25.jar/de.maxhenkel.voicechat.plugins.PluginManager.onListenerAudio(PluginManager.java:126) ~[voicechat-bukkit-2.5.25.jar:?]
        at voicechat-bukkit-2.5.25.jar/de.maxhenkel.voicechat.voice.server.Server.sendSoundPacket(Server.java:383) ~[voicechat-bukkit-2.5.25.jar:?]
        at voicechat-bukkit-2.5.25.jar/de.maxhenkel.voicechat.voice.server.Server.broadcast(Server.java:431) ~[voicechat-bukkit-2.5.25.jar:?]
        at voicechat-bukkit-2.5.25.jar/de.maxhenkel.voicechat.voice.server.Server.processProximityPacket(Server.java:379) ~[voicechat-bukkit-2.5.25.jar:?]
        at voicechat-bukkit-2.5.25.jar/de.maxhenkel.voicechat.voice.server.Server.processMicPacket(Server.java:316) ~[voicechat-bukkit-2.5.25.jar:?]
        at voicechat-bukkit-2.5.25.jar/de.maxhenkel.voicechat.voice.server.Server.onMicPacket(Server.java:303) ~[voicechat-bukkit-2.5.25.jar:?]
        at voicechat-bukkit-2.5.25.jar/de.maxhenkel.voicechat.voice.server.Server$ProcessThread.run(Server.java:269) ~[voicechat-bukkit-2.5.25.jar:?]
[02:02:03 INFO]: [Not Secure] <.BIGYan008> ils sont ou les sotie de pillards
[02:02:04 INFO]: [Geyser-Spigot] Player connected with username Blanconoco
[02:02:04 INFO]: [Geyser-Spigot] Blanconoco (logged in as: Blanconoco) has connected to the Java server
[02:02:04 INFO]: [floodgate] Floodgate player logged in as .Blanconoco joined (UUID: 00000000-0000-0000-0009-01f9d2786732)
[02:02:04 INFO]: .Blanconoco joined the game
[02:02:04 INFO]: .Blanconoco[/209.226.118.236:0] logged in with entity id 1079 at ([world]181.03961, 71.0625, 159.01135)

**Versions (please complete the following information):**
- Minecraft: 
- Loader paper-1.21.3-44.jar
- Simple Voice Chat:  Simple Voice Chat 2.5.25
- Simple Voice Chat Discord Bridge: voicechat-discord-paper-3.0.5.jar

**Additional context**

**Comment by amsam0** [comment]
Known issue. See #75. I might be able to get the PR to a mergeable state sometime in the next few weeks, but I'm not sure.

**Comment by amsam0** [comment]
@laroweb @Lets-game6531 3.0.6 is now released, which should fix issues with 1.21.3+. Please make a new github issue if you have any issues since this release is relatively untested.

Paper: https://modrinth.com/plugin/simple-voice-chat-discord-bridge/version/3.0.6
Fabric: https://modrinth.com/plugin/simple-voice-chat-discord-bridge/version/tDPLx71i
